local_costmap:
   global_frame: odom_combined
   robot_base_frame: base_footprint
   update_frequency: 3.0
   publish_frequency: 3.0
   inflation_radius: 0.2
   robot_radius: 0.2
   width: 3.0
   height: 3.0
   resolution: 0.05
   static_map: false
   rolling_window: true
